language:
  - cpp

os:
  - osx

compiler:
  - clang

before_install:
  - make deps

script:
  - make
  - make test

cache:
  directories:
    - .sources
    - /Library/Caches/Homebrew
    - /usr/local/Cellar
